### ISSUE TITLE
KeyValuePair enumerator

### ISSUE THREAD

**Issue by Kizaemon** [SoftCircuits/OrderedDictionary#2]
Dear SoftCircuits,

thank you for your clean and neat implementation of the ordered dictionary.
I wonder why the for each construct does not pickup the KeyValuePair version of the GetEnumerator?

```
            OrderedDictionary<int, string> dictionary = new OrderedDictionary<int, string> {
                [101] = "Bob Smith",
                [127] = "Gary Wilson",
                [134] = "Ann Carpenter",
                [187] = "Bill Jackson",
                [214] = "Cheryl Hansen",
            };

            foreach (KeyValuePair<int, string> kvp in dictionary) { // does not work here
                int n = kvp.Key;
                string s = kvp.Value;
            }

```

In this example the foreach enumerates all values, not the KVP<K,V>.

This is a difference from the normal C# dictionary behavior.
So the OrderedDictionary cannot be used as a drop-in replacement for C#'s Dictionary.

Or maybe I am doing something wrong?

**Comment by Kizaemon** [comment]
![image](https://user-images.githubusercontent.com/38976573/206698083-0b7d09bc-6018-4607-b5c7-cdd2d05f23b8.png)

**Comment by SoftCircuits** [comment]
The default enumerator just enumerates the values.

But you can do what you want with a typecast.

```cs
foreach (KeyValuePair<int, string> pair in (IEnumerable<KeyValuePair<int, string>>)dictionary)
{
    int n = pair.Key;
    string s = pair.Value;
}
```

At this point, I'm not sure what should be the default behavior. Or if I would break many people's code if I changed it.

**Comment by SoftCircuits** [comment]
FYI, in version 3.0.0, using `foreach` directly on the collection will enumerate the underlying `KeyValuePair<TKey, TValue>`s in the collection in the order the items were added. This more closely matches the value of `Dictionary<TKey, TValue>`. To enumerate the keys or values, use the `Keys` or `Values` properties.

**Comment by Kizaemon** [comment]
Thank you for prompt reply.
I think it is working now!
