### ISSUE TITLE
Implement IReadOnlyDictionary

### ISSUE THREAD

**Issue by josago97** [SoftCircuits/OrderedDictionary#6]
Hello, could the IReadOnlyDictionary interface be implemented in the dictionary to be able to make more abstract code? Thank you.

**Comment by SoftCircuits** [comment]
@josago97 I will implement this request. I'm trying to figure out the best way to deal with a couple of technical issues, so it may take a bit to completely. I'll post here once an update has been posted.

**Comment by SoftCircuits** [comment]
This has been implemented in 3.1.0. Thanks.
